### ISSUE TITLE
Still can't play the game.

### ISSUE THREAD

**Issue by MORADNAXOSH** [HuniePotHeads/HuniePop-x64#3]
**Describe the bug**
When I try to merge the files, the only options I get are "Stop" and "Replace". I'm also given the "do not have permission to open this" message when I try to use it. And when I'm trying to open huniepop, it gives me the same steam message it always does which is "Mac OS no longer supports 32-bit apps". Please help and thank you very much.

**To Reproduce**
Didn't really do anything in the game files other than trying to add the contents but it didn't really work.

**Expected behavior**
I expected for the game to be able to open with it.

**System information (please fill out as many questions as you can):**
 - Game version: [e.g. HuniePop 1.2.0 Humble Bundle, GOG, physical release, etc.]
 - System OS: macOS Big Sur 11.1
 - System model: 13-inch Macbook Pro 2020 Model
 - System CPU: Intel Core i5 
 - System GPU: Intel Iris Plus Graphics 1536 MB
 - Display: 13"

**Comment by TheLounger** [comment]
It is known to fail with the Steam version. This is clearly stated in the readme.
